# ============  hub3 elasticsearch.yml  ===============
#
# ==============================================================


# ---------------------------------- Cluster -----------------------------------
# ALWAYS change this to include a unique name
cluster.name: narthex 

# ------------------------------------ Node ------------------------------------
#
# Use a descriptive name for the node:
#
node.name: prod


# ----------------------------------- Paths ------------------------------------
#
#  These settings are set in /etc/defaults/elasticsearch


# ----------------------------------- Memory -----------------------------------
#
# Lock the memory on startup:
#
#bootstrap.memory_lock: true
#
# Make sure that the heap size is set to about half the memory available
# on the system and that the owner of the process is allowed to use this
# limit.
#
# Elasticsearch performs poorly when the system is swapping the memory.
#
# Memory settings are now in /etc/elasticsearch/jvm.options
#
# ---------------------------------- Network -----------------------------------
#
# Set the bind address to a specific IP (IPv4 or IPv6):
#


# ====>> Could the following two be the problem?

# bind to all devices, firewall decides if external access is allowed
network.bind_host: 0.0.0.0

# for same server deploy, this will be 127.0.0.1, for clusters it will be the primary net device
network.publish_host: 127.0.0.1


#
# Set a custom port for HTTP:
#
http.port: 9200
#
# For more information, see the documentation at:
# <http://www.elastic.co/guide/en/elasticsearch/reference/current/modules-network.html>
#

# --------------------------------- Discovery ----------------------------------
#
# Pass an initial list of hosts to perform discovery when new node is started:
# The default list of hosts is ["127.0.0.1", "[::1]"]
#
discovery.zen.ping.unicast.hosts: [ "127.0.0.1",  ]


#
# Prevent the "split brain" by configuring the majority of nodes (total number of nodes / 2 + 1):
#
discovery.zen.minimum_master_nodes: 1



# ---------------------------------- Various -----------------------------------
#

#
# Require explicit names when deleting indices:
#
action.destructive_requires_name: true


#
# Custom settings, not always used
#
